### ISSUE TITLE
Relax cuda-python run dependencies

### ISSUE THREAD

**Issue by bdice** [conda-forge/cuda-python-feedstock#66]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

I faced an issue with cuda-python, where the `run` dependencies were requiring `cuda-cudart` and `cuda-nvrtc` and resulting in an undesired environment solution that crossed channel priorities. https://github.com/rapidsai/integration/pull/695

The current run dependencies for `linux-64/cuda-python-12.3.0-py38hd750a71_0.conda` are:
```
__glibc >=2.17,<3.0.a0, cuda-cudart >=12.3.101,<13.0a0, cuda-nvrtc >=12.3.107,<13.0a0, cuda-version >=12,<13.0a0, libgcc-ng >=12, libstdcxx-ng >=12, python >=3.8,<3.9.0a0, python_abi 3.8.* *_cp38
```

However, it doesn't seem that the cuda-python package needs the run dependencies on `cuda-cudart` or `cuda-nvrtc`. They're not dynamically linked, and they're not explicitly listed as `run` requirements. They are coming from run-exports of dependencies in the `host` section: https://github.com/conda-forge/cuda-python-feedstock/blob/a5117f8f1fe8a5914180102ebff153ce7c6c710b/recipe/meta.yaml#L47-L49

From discussions with @jakirkham, the cuda-python package should be able to leverage CUDA Enhanced Compatibility, meaning that we should be able to add `ignore_run_exports_from` for dev packages like `cuda-cudart-dev`.

### Installed packages

```shell
n/a
```

### Environment info

```shell
n/a
```

**Comment by leofang** [comment]
> However, it doesn't seem that the cuda-python package needs the run dependencies on `cuda-cudart` or `cuda-nvrtc`. They're not dynamically linked, and they're not explicitly listed as `run` requirements. 

CUDA Python reimplements CUDA runtime so not depending on `cuda-cudart` is fine. But it dynamically links to NVRTC so we still need to keep the latter in the run section.

**Comment by jakirkham** [comment]
> But it dynamically links to NVRTC so we still need to keep the latter in the run section.

Looking at the build logs, see the following [on CI]( https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=866632&view=logs&j=d0d954b5-f111-5dc4-4d76-03b6c9d0cf7e&t=779a0c34-7b19-5ccb-5da7-fe4579c91392 ):

```python
WARNING (cuda-python): dso library package conda-forge/linux-64::cuda-nvrtc==12.3.107=hd3aeb46_0 in requirements/run but it is not used (i.e. it is overdepending or perhaps statically linked? If that is what you want then add it to `build/ignore_run_exports`)
WARNING (cuda-python): dso library package conda-forge/linux-64::cuda-cudart==12.3.101=hd3aeb46_0 in requirements/run but it is not used (i.e. it is overdepending or perhaps statically linked? If that is what you want then add it to `build/ignore_run_exports`)
```

Also seeing [this `dlopen` logic for `nvrtc`]( https://github.com/NVIDIA/cuda-python/blob/dfd31fa609b9c81bcff925824f38531ab3c96706/cuda/_cuda/cnvrtc.pyx.in#L45-L60 )

Though please let us know if we are still missing something

**Comment by leofang** [comment]
I am not sure what would that be different from what I said above. Are you suggesting NVRTC should be listed in `run_constrained` not `run`? If so, I am fine with it.

**Comment by jakirkham** [comment]
It doesn't appear to be dynamically linking to `nvrtc`. It is using `dlopen`

`cuda-nvrtc` can still be in `run`, but `cuda-nvrtc` doesn't need a pin (it is not dynamically linked)

**Comment by leofang** [comment]
OK, sorry for using the wrong terminology if we want to be pedantic here. It's "runtime" not "dynamically" linked. But it doesn't change the fact that `cuda-nvrtc` needs to be at least added to `run_constained` using `pin_compatible`, can we agree on this? Otherwise, if there's any API breaking change in NVRTC (despite highly unlikely), the Python binding would not work and all sorts of weird errors could happen. 

This was similarly done in [CuPy v13](https://github.com/conda-forge/cupy-feedstock/pull/241), where everything is also technically runtime linked (through the Python import system instead of `dlopen`), and we've seen and agreed with the treatment there.

**Comment by jakirkham** [comment]
Dynamic linking and `dlopen` have important differences that affect the behavior of the resulting binary. Think it is important for us to distinguish the two

If you have already, could you please read over the code linked above ( https://github.com/conda-forge/cuda-python-feedstock/issues/66#issuecomment-1918125390 )? The `dlopen` logic is including NVRTC's SONAME there. If NVRTC were to break their API/ABI, then they would change the SONAME (meaning it wouldn't be `dlopen`ed in this case)

**Comment by leofang** [comment]
> If you have not already, could you please read over the code linked above ( [#66 (comment)](https://github.com/conda-forge/cuda-python-feedstock/issues/66#issuecomment-1918125390) )? The `dlopen` logic is including NVRTC's SONAME there.

Sorry, but I have a you-know-which project that implements exactly the same approach (after studying CUDA Python carefully) so you can assume my utter familiarity with the code. I know what I was talking (and I can tell you where CUDA Python can improve) 🙂

The point is, in order to implement runtime linking through `dlopen`/`dlsym`, we need to make strong assumptions about the ABI compatibility (all function signatures must not change, all struct sizes and layouts must not change, etc). I am against us lowering the guard only in CUDA Python, while keeping a high bar for safety considerations elsewhere. The standard treatment in conda-forge would have been 
```yaml
run_constrained:
  - {{ pin_compatible('cuda-nvrtc', max_pin='x') }}
```
to say the least. What's the issue that we can't implement this change?

> If NVRTC were to break their API/ABI, then they would change the SONAME (meaning it wouldn't be `dlopen`ed in this case)

This is not necessarily true. I've seen multiple CUDA API/ABI incidents in the past, in both CUDA runtime and libraries. There was no one-size-fit-all sanity checks that could possibly capture all these accidents, and what we do on the packaging side is the last line of defense. What I am asking is simply to proceed with caution.

**Comment by jakirkham** [comment]
>> If you have not already, could you please read over the code linked above ( https://github.com/conda-forge/cuda-python-feedstock/issues/66#issuecomment-1918125390 )? The dlopen logic is including NVRTC's SONAME there.
>
> Sorry, but I have a you-know-which project that implements exactly the same approach (after studying CUDA Python carefully) so you can assume my utter familiarity with the code. I know what I was talking (and I can tell you where CUDA Python can improve) 🙂

Sorry if that came off as blunt. Wanted to be sure we were looking at the same thing as it felt like we were talking past each other

> What's the issue that we can't implement this change?

Have included you in an offline discussion where this came up. At this point think it is better to discuss there for a bit before discussing here further
